all: clear build
	g++ -Wall -o build/myprog src/Figura.cpp src/Patrulater.cpp src/Pentagon.cpp src/Point.cpp src/Triunghi.cpp src/Util.cpp src/Cerc.cpp main.cpp
build:
	mkdir build

clear:
	rm -rf build